# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TPFEngenharia
                                 A QGIS plugin
 Plugin da TPF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-14
        copyright            : (C) 2023 by Sanderllan Costa
        email                : sanderllan.costa@tpfe.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Sanderllan Costa'
__date__ = '2023-02-14'
__copyright__ = '(C) 2023 by Sanderllan Costa'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TPFEngenharia class from file TPFEngenharia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tpfeng import TPFEngenhariaPlugin
    return TPFEngenhariaPlugin()
